# Generated by Django 5.1.5 on 2025-01-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=130)),
                ('user_email', models.EmailField(max_length=50, unique=True)),
                ('user_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user_address', models.TextField(blank=True, null=True)),
                ('user_date_of_birth', models.DateField(blank=True, null=True)),
                ('user_registration_date', models.DateField(auto_now_add=True)),
                ('user_age', models.IntegerField(blank=True, null=True)),
                ('user_gender', models.CharField(blank=True, max_length=6, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('email_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
