# Generated by Django 4.2.5 on 2025-02-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ser_provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='aadhar_card',
            field=models.ImageField(blank=True, null=True, upload_to='Ser_provider/identification_docs/'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='electricity_bill',
            field=models.ImageField(blank=True, null=True, upload_to='Ser_provider/identification_docs/'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='police_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='Ser_provider/identification_docs/'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Ser_provider/profile_pics/'),
        ),
    ]
