# Generated by Django 4.2.5 on 2025-02-15 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ser_provider', '0002_remove_serviceprovider_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='aadhar_card',
            field=models.ImageField(blank=True, null=True, upload_to='Ser_provider/identification_docs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='electricity_bill',
            field=models.ImageField(blank=True, null=True, upload_to='Ser_provider/identification_docs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='police_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='Ser_provider/identification_docs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
