# Generated by Django 4.2.5 on 2025-02-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ser_provider', '0003_alter_serviceprovider_aadhar_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='aadhar_card',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='electricity_bill',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='police_certificate',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='aadharCard',
            field=models.ImageField(blank=True, null=True, upload_to='identification_docs/'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='electricityBill',
            field=models.ImageField(blank=True, null=True, upload_to='identification_docs/'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='policeCertificate',
            field=models.ImageField(blank=True, null=True, upload_to='identification_docs/'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterModelTable(
            name='serviceprovider',
            table='serviceProvider',
        ),
    ]
