# Generated by Django 5.0.4 on 2025-03-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ser_provider', '0004_remove_serviceprovider_aadhar_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='policeCertificate',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='Policeclearancecertificate',
            field=models.FileField(blank=True, null=True, upload_to='identification_docs/'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='aadharCard',
            field=models.FileField(blank=True, null=True, upload_to='identification_docs/'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='electricityBill',
            field=models.FileField(blank=True, null=True, upload_to='identification_docs/'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterModelTable(
            name='serviceprovider',
            table='serviceprovider',
        ),
    ]
